### ISSUE TITLE
Incorrect syntax near ')'. on subsequent saves

### ISSUE THREAD

**Issue by AndyBoot** [callumbwhyte/meganav#51]
- Umbraco 9.3.1
- Our.Umbraco.Meganav 3.0.1

Newly installed and using for the first time based on the umbraCoffee demo #H5YR !

Applied the Meganav property to a field, configured it (correctly with the minimum amount of settings I believe), clicked save which worked successfully for the first time. Unfortunately subsequent saves keep giving me the following error:
![image](https://user-images.githubusercontent.com/82056925/157645273-4aa874a5-8384-44ee-a3c5-49b638f9bf71.png)

For reference here's the configuration:
![image](https://user-images.githubusercontent.com/82056925/157645403-389b92c4-f529-4739-8f64-6d7d2ea245b4.png)

Full stacktrace:

> at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)
   at NPoco.Database.ExecuteScalar[T](String sql, CommandType commandType, Object[] args)
   at NPoco.Database.ExecuteScalar[T](Sql Sql)
   at NPoco.Database.ExecuteScalar[T](String sql, Object[] args)
   at NPoco.Database.PageImp[T,TRet](Int64 page, Int64 itemsPerPage, String sql, Object[] args, Func`3 executeQueryFunc)
   at NPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, String sql, Object[] args)
   at NPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, Sql sql)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentRepositoryBase`3.GetPage[TDto](IQuery`1 query, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, Func`2 mapDtos, Sql`1 filter, Ordering ordering)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.GetPage(IQuery`1 query, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, IQuery`1 filter, Ordering ordering)
   at Umbraco.Cms.Core.Services.Implement.ContentService.GetPagedOfTypes(Int32[] contentTypeIds, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, IQuery`1 filter, Ordering ordering)
   at Our.Umbraco.Meganav.Migrations.LegacyValueMigrator.MigrateContentValues(IDataType dataType)
   at Our.Umbraco.Meganav.Migrations.LegacyDataTypeChangingHandler.Handle(DataTypeSavingNotification notification)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore(IEnumerable`1 allHandlers, INotification notification)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle(INotification notification, ServiceFactory serviceFactory, Action`2 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification](TNotification notification)
   at Umbraco.Cms.Core.Events.ScopedNotificationPublisher.PublishCancelable(ICancelableNotification notification)
   at Umbraco.Cms.Core.Services.Implement.DataTypeService.Save(IDataType dataType, Int32 userId)
   at Umbraco.Cms.Web.BackOffice.Controllers.DataTypeController.PostSave(DataTypeSave dataType)
   at lambda_method1528(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by callumbwhyte** [comment]
Hey @AndyBoot,

Thanks for using Meganav!

From the stack trace here it looks like the `LegacyValueMigrator` is firing unexpectedly. Can I confirm, this occurs when saving the data type for a 2nd time? The property editor is working / saving as expected?

Cheers,
Callum

**Comment by callumbwhyte** [comment]
Glad you found the solution @AndyBoot!
